package com.pulsepoint.models;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents an administrator in the PulsePoint system.
 * Extends User with admin-specific attributes and methods.
 */
public class Administrator extends User {

    private String adminId;
    private List<AuditLog> auditLogs;

    public Administrator(String userId, String fullName, String email,
                         String passwordHash, String phone) {
        super(userId, fullName, email, passwordHash, phone, "Administrator");
        this.adminId = userId;
        this.auditLogs = new ArrayList<>();
    }

    public Doctor createDoctorAccount(String doctorId, String fullName, String email,
                                       String passwordHash, String phone,
                                       String specialisation, String qualifications) {
        Doctor doctor = new Doctor(doctorId, fullName, email, passwordHash,
                                   phone, specialisation, qualifications);
        System.out.println("Doctor account created by admin: " + getFullName());
        return doctor;
    }

    public void deactivateUserAccount(User user) {
        user.deactivateAccount();
        System.out.println("Admin " + getFullName() + " deactivated account: " + user.getFullName());
    }

    public void reactivateUserAccount(User user) {
        user.reactivateAccount();
        System.out.println("Admin " + getFullName() + " reactivated account: " + user.getFullName());
    }

    public AnalyticsReport viewAnalytics() {
        AnalyticsReport report = new AnalyticsReport(
            "RPT-" + System.currentTimeMillis(),
            0, 0.0f, 0.0f
        );
        System.out.println("Analytics report generated by admin: " + getFullName());
        return report;
    }

    public List<AuditLog> viewAuditLogs() {
        System.out.println("Audit logs accessed by admin: " + getFullName());
        return auditLogs;
    }

    public void addAuditLog(AuditLog log) {
        this.auditLogs.add(log);
    }

    // Getters
    public String getAdminId() { return adminId; }

    @Override
    public String toString() {
        return "Administrator{adminId='" + adminId + "', fullName='" + getFullName() + "'}";
    }
}