package com.pulsepoint.models;

import java.time.LocalDateTime;

/**
 * Represents an analytics report generated by an Administrator.
 * Contains clinic performance metrics and supports export functionality.
 */
public class AnalyticsReport {

    private String reportId;
    private LocalDateTime generatedAt;
    private int totalAppointments;
    private float completionRate;
    private float noShowRate;
    private String format; // PDF, CSV
    private String status; // NotGenerated, Generating, Generated, Downloaded, Expired, Failed

    public AnalyticsReport(String reportId, int totalAppointments,
                           float completionRate, float noShowRate) {
        this.reportId = reportId;
        this.totalAppointments = totalAppointments;
        this.completionRate = completionRate;
        this.noShowRate = noShowRate;
        this.generatedAt = LocalDateTime.now();
        this.status = "NotGenerated";
        this.format = "PDF";
    }

    public void generate() {
        this.status = "Generating";
        System.out.println("Generating analytics report " + reportId + "...");

        // Simulate report generation
        this.status = "Generated";
        this.generatedAt = LocalDateTime.now();
        System.out.println("Report " + reportId + " generated successfully.");
        System.out.println("Total Appointments: " + totalAppointments);
        System.out.println("No-Show Rate: " + noShowRate + "%");
    }

    public String export(String format) {
        if (!status.equals("Generated")) {
            System.out.println("Report must be generated before exporting.");
            return null;
        }
        this.format = format;
        this.status = "Downloaded";
        String filename = "PulsePoint_Report_" + reportId + "." + format.toLowerCase();
        System.out.println("Report exported as: " + filename);
        return filename;
    }

    public void applyFilter(String filterType, String filterValue) {
        System.out.println("Applying filter: " + filterType + " = " + filterValue);
        // Filter logic would re-query the database in production
    }

    // Getters and Setters
    public String getReportId() { return reportId; }
    public LocalDateTime getGeneratedAt() { return generatedAt; }
    public int getTotalAppointments() { return totalAppointments; }
    public float getCompletionRate() { return completionRate; }
    public float getNoShowRate() { return noShowRate; }
    public String getFormat() { return format; }
    public String getStatus() { return status; }

    public void setTotalAppointments(int totalAppointments) { this.totalAppointments = totalAppointments; }
    public void setCompletionRate(float completionRate) { this.completionRate = completionRate; }
    public void setNoShowRate(float noShowRate) { this.noShowRate = noShowRate; }

    @Override
    public String toString() {
        return "AnalyticsReport{reportId='" + reportId + "', totalAppointments=" + totalAppointments +
               ", completionRate=" + completionRate + ", noShowRate=" + noShowRate +
               ", status='" + status + "'}";
    }
}